/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processing_glvideo_GLVideo */

#ifndef _Included_processing_glvideo_GLVideo
#define _Included_processing_glvideo_GLVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processing_glvideo_GLVideo
 * Method:    gstreamer_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_processing_glvideo_GLVideo_gstreamer_1init
  (JNIEnv *, jclass);

/*
 * Class:     processing_glvideo_GLVideo
 * Method:    gstreamer_open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_processing_glvideo_GLVideo_gstreamer_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     processing_glvideo_GLVideo
 * Method:    gstreamer_available
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_processing_glvideo_GLVideo_gstreamer_1available
  (JNIEnv *, jobject, jlong);

/*
 * Class:     processing_glvideo_GLVideo
 * Method:    gstreamer_getFrame
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_processing_glvideo_GLVideo_gstreamer_1getFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     processing_glvideo_GLVideo
 * Method:    gstreamer_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_processing_glvideo_GLVideo_gstreamer_1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
